# Generated by Django 2.0.1 on 2018-07-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password_md5', models.CharField(max_length=100)),
                ('invitation_code', models.CharField(max_length=4)),
                ('inviter', models.CharField(default='', max_length=4)),
                ('avatar_url', models.CharField(default='', max_length=200)),
                ('eos_address', models.CharField(default='', max_length=100)),
                ('eth_address', models.CharField(default='', max_length=100)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
